[package]
name = "jen"
version = "0.1.0"
description = "jen"
authors = ["sehaz"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "jen_lib"
crate-type = ["staticlib", "cdylib", "rlib"]

[build-dependencies]
tauri-build = { version = "2", features = [] }

[dependencies]
tauri = { version = "2", features = ["tray-icon"] }
tauri-plugin-opener = "2"
serde = { version = "1", features = ["derive"] }
serde_json = "1"
cpal = "0.15"
rustpotter = "3.0"
rand = "=0.8.6"
half = "=2.3.1"
thiserror = "2"
tokio = { version = "1", features = ["time"] }
rodio = { version = "0.19", features = ["mp3"] }
lazy_static = "1.5"
log = "0.4"
env_logger = "0.11"
tauri-plugin-shell = "2"
tauri-plugin-global-shortcut = "2"
tauri-plugin-store = "2"
windows = { version = "0.62.2", features = [
    "Win32_Foundation", 
    "Win32_UI_WindowsAndMessaging",
    "Media_Control",
    "Foundation",
    "Foundation_Collections",
    "Win32_System_Threading",
    "Win32_UI_Input_KeyboardAndMouse",
    "Win32_Media_Audio"
] }

[target.'cfg(not(any(target_os = "android", target_os = "ios")))'.dependencies]
tauri-plugin-autostart = "2"
